### ISSUE TITLE
403 On Default Ads Report

### ISSUE THREAD

**Issue by BenGoliath** [google-marketing-solutions/margin-protection#43]
I am receiving a 403 error on my Default Ads report that was working last week.

"ERROR: Error fetching report {
  ""error"": {
    ""code"": 403,
    ""message"": ""Forbidden"",
    ""errors"": [
      {
        ""message"": ""Forbidden"",
        ""domain"": ""global"",
        ""reason"": ""forbidden""
      }
    ]
  }
}
"

**Comment by anaesqueda** [comment]
Hi Ben,

Thanks for reaching out. Could you please verify that your profile id in Campaign Manager still has access to view/edit/create reports? The solution has not been updated and I would like to verify if the problem is related to access in CM.

Thanks!

**Comment by BenGoliath** [comment]
Hi Ana!

My access to CM looks to be the same as last week when the tool was working, I am still listed as a top level administrator on that profile. I have tried a manual run and the pre scheduled run today, both unsuccessful.

Thank you,

Ben Goliath
Director of Technology
7809160373
________________________________

**Comment by anaesqueda** [comment]
Hi Ben,

I just created a new copy of the template and everything is working as expected on my end. Could you please send an email to: launch-monitor-users@google.com with the link to your copy? I can take a quick look.

Thank you!
