### ISSUE TITLE
Report details [V3 // PROD] DV360 Launch Monitor.

### ISSUE THREAD

**Issue by Gustavorm545** [google-marketing-solutions/margin-protection#66]
Hi,

We are using the [V3 // PROD] DV360 Launch Monitor version for receiving notifications on DV360 campaigns. The report via email works fine but It would be ideal having additional information like Campaign ID, Insertion Order ID and Line Item ID in a table format, so it makes easier to find the campaign/insertion order/line item that is having issues directly on the platform. By now we are receiving something like this:

The following errors were found:
----------
Budget Pacing by Days Ahead/Behind (Line Item):
----------
- Pace OK; Pacing Type PACING_TYPE_ASAP != PACING_TYPE_AHEAD
- Pace OK; Pacing Type PACING_TYPE_ASAP != PACING_TYPE_AHEAD
- -19.94390804497537% (< 0%); Pacing Type PACING_TYPE_EVEN !=  
PACING_TYPE_AHEAD
- -12.98076690755422% (< 0%); Pacing Type PACING_TYPE_EVEN !=  
----------
Budget Pacing by Percent Ahead:
----------
- -19.943987591156535% (< 0%)
- -10.96866553066002% (< 0%); Pacing Type PACING_TYPE_ASAP !=  
PACING_TYPE_AHEAD
- -24.78527281089472% (< 0%)
----------
Budget Per Day:
----------
- 200126.2578
----------
Impressions by Geo Target:
----------
- 1
- 1

Thanks in advance.

**Comment by smcjones** [comment]
@Gustavorm545 this should now be resolved, so I am closing this issue. It's been updated in the template. Please let me know if you have any other issues by reopening this issue or creating a new one.

Thanks!

Sean
